export const US_CITIES = [
  { city: "New York", state: "NY" },
  { city: "Los Angeles", state: "CA" },
  { city: "Chicago", state: "IL" },
  { city: "Houston", state: "TX" },
  { city: "Phoenix", state: "AZ" },
  { city: "Philadelphia", state: "PA" },
  { city: "San Antonio", state: "TX" },
  { city: "San Diego", state: "CA" },
  { city: "Dallas", state: "TX" },
  { city: "San Jose", state: "CA" },
  { city: "Austin", state: "TX" },
  { city: "Jacksonville", state: "FL" },
  { city: "Fort Worth", state: "TX" },
  { city: "Columbus", state: "OH" },
  { city: "Charlotte", state: "NC" },
  { city: "San Francisco", state: "CA" },
  { city: "Indianapolis", state: "IN" },
  { city: "Seattle", state: "WA" },
  { city: "Denver", state: "CO" },
  { city: "Washington", state: "DC" },
  { city: "Boston", state: "MA" },
  { city: "El Paso", state: "TX" },
  { city: "Nashville", state: "TN" },
  { city: "Detroit", state: "MI" },
  { city: "Oklahoma City", state: "OK" },
  { city: "Portland", state: "OR" },
  { city: "Las Vegas", state: "NV" },
  { city: "Memphis", state: "TN" },
  { city: "Louisville", state: "KY" },
  { city: "Baltimore", state: "MD" },
  { city: "Milwaukee", state: "WI" },
  { city: "Albuquerque", state: "NM" },
  { city: "Tucson", state: "AZ" },
  { city: "Fresno", state: "CA" },
  { city: "Mesa", state: "AZ" },
  { city: "Sacramento", state: "CA" },
  { city: "Atlanta", state: "GA" },
  { city: "Kansas City", state: "MO" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Miami", state: "FL" },
  { city: "Raleigh", state: "NC" },
  { city: "Omaha", state: "NE" },
  { city: "Long Beach", state: "CA" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Oakland", state: "CA" },
  { city: "Minneapolis", state: "MN" },
  { city: "Tulsa", state: "OK" },
  { city: "Tampa", state: "FL" },
  { city: "Arlington", state: "TX" },
  { city: "New Orleans", state: "LA" },
  { city: "Wichita", state: "KS" },
  { city: "Cleveland", state: "OH" },
  { city: "Bakersfield", state: "CA" },
  { city: "Aurora", state: "CO" },
  { city: "Anaheim", state: "CA" },
  { city: "Honolulu", state: "HI" },
  { city: "Santa Ana", state: "CA" },
  { city: "Riverside", state: "CA" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Lexington", state: "KY" },
  { city: "Stockton", state: "CA" },
  { city: "Henderson", state: "NV" },
  { city: "Saint Paul", state: "MN" },
  { city: "St. Louis", state: "MO" },
  { city: "Cincinnati", state: "OH" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Greensboro", state: "NC" },
  { city: "Anchorage", state: "AK" },
  { city: "Plano", state: "TX" },
  { city: "Lincoln", state: "NE" },
  { city: "Orlando", state: "FL" },
  { city: "Irvine", state: "CA" },
  { city: "Newark", state: "NJ" },
  { city: "Toledo", state: "OH" },
  { city: "Durham", state: "NC" },
  { city: "Chula Vista", state: "CA" },
  { city: "Fort Wayne", state: "IN" },
  { city: "Jersey City", state: "NJ" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Laredo", state: "TX" },
  { city: "Madison", state: "WI" },
  { city: "Chandler", state: "AZ" },
  { city: "Buffalo", state: "NY" },
  { city: "Lubbock", state: "TX" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Reno", state: "NV" },
  { city: "Glendale", state: "AZ" },
  { city: "Gilbert", state: "AZ" },
  { city: "Winston-Salem", state: "NC" },
  { city: "North Las Vegas", state: "NV" },
  { city: "Norfolk", state: "VA" },
  { city: "Chesapeake", state: "VA" },
  { city: "Garland", state: "TX" },
  { city: "Irving", state: "TX" },
  { city: "Hialeah", state: "FL" },
  { city: "Fremont", state: "CA" },
  { city: "Boise", state: "ID" },
  { city: "Richmond", state: "VA" },
  { city: "Baton Rouge", state: "LA" },
  { city: "Spokane", state: "WA" },
];

export const NICHES = [
  { id: "dentist", name: "Dentist" },
  { id: "restaurant", name: "Restaurant" },
  { id: "lawyer", name: "Lawyer" },
  { id: "plumber", name: "Plumber" },
  { id: "electrician", name: "Electrician" },
  { id: "hvac", name: "HVAC" },
  { id: "roofer", name: "Roofer" },
  { id: "landscaping", name: "Landscaping" },
  { id: "accounting", name: "Accounting" },
  { id: "real_estate", name: "Real Estate" },
  { id: "gym", name: "Gym & Fitness" },
  { id: "spa", name: "Spa" },
  { id: "salon", name: "Salon" },
  { id: "auto_repair", name: "Auto Repair" },
];
